import './globals.css';
import '../styles/globals.scss';
import { Inter } from 'next/font/google';
import Layout from '@/components/layout';
import { AuthProvider } from '@/context/auth';
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	axios.defaults.withCredentials = true;
	return (
		<html lang='en'>
			<body className={inter.className} suppressHydrationWarning={true}>
				<AuthProvider>
					<Layout>{children}</Layout>
				</AuthProvider>
			</body>
		</html>
	);
}
